### ISSUE TITLE
ERR_HTTP2_GOAWAY_SESSION with POST requests

### ISSUE THREAD

**Issue by duffn** [grantila/fetch-h2#63]
We occasionally experience an issue that results in the below logs during a POST request.

```
2019-10-09T14:58:18 Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created after receiving a GOAWAY
2019-10-09T14:58:18 at ClientHttp2Session.request (internal/http2/core.js:1556:13)
2019-10-09T14:58:18 at doFetch (/app/services/myapp/node_modules/fetch-h2/dist/lib/fetch-http2.js:25:34)
```

This POST request is unremarkable.

```
resp = await fetch(`/thing`, {
    method: `POST`,
    headers: {
        "x-header-1": "thing1",
        "x-header-2": "thing2",
    },
})
```

I see that in the issue below it was stated that POST would not be fixed. Is there any change to this thought?

https://github.com/grantila/fetch-h2/issues/19#issuecomment-442253479

**Comment by jamo** [comment]
Hi @grantila, we are still experiencing this issue occasionally. Is there anything we can do to help debug this further? Or any ideas about how we could gracefully detect this and restart the connection.
