### ISSUE TITLE
disconnectAll() throws "Error: unexpected end of file"

### ISSUE THREAD

**Issue by stefan-guggisberg** [grantila/fetch-h2#97]
To reproduce:

```js
const { fetch, disconnectAll } = require('fetch-h2');

(async function () {
  let resp = await fetch('https://api.fastly.com/public-ip-list');
  // don't read body
  await disconnectAll();  // => throws error
}());
```

Running above code gives the following error:

```js
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
Emitted 'error' event on Gunzip instance at:
    at Zlib.zlibOnError [as onerror] (zlib.js:183:8) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

**Comment by grantila** [comment]
This I _think_ is actually fixed, although not sure in which version. I can't personally reproduce. Please re-open if you can reproduce it again (and with which Node version), thanks!
